name: Java CI with Gradle

on:
 push:
    branches:
       - '*'
 pull_request:
    branches:
      - '*'
 workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: chmod -R 777 *
      run: chmod -R 777 *
    - name: Build plugin
      run:  ./gradlew :buildPlugin --warning-mode all --info --stacktrace
